services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb
    environment:
      - ARANGO_PASSWORD=${ARANGO_PASSWORD}
    ports:
      - "8529:8529"
    volumes:
      - arangodb-data:/var/lib/arangodb3
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-arango-backend
    environment:
      - ARANGO_HOST=${ARANGO_HOST}
      - ARANGO_USER=${ARANGO_USER}
      - ARANGO_PASSWORD=${ARANGO_PASSWORD}
      - ARANGO_DB=${ARANGO_DB}
      - API_PORT=${API_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - .:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - arangodb
    command: ./wait-for-arangodb.sh http://arangodb:8529 poetry run python -m backend.main

volumes:
  arangodb-data:
      dockerfile: Dockerfile.android
    container_name: android-emulator
    network_mode: "host"
    environment:
      - ANDROID_HOME=/opt/android-sdk
    devices:
      - /dev/kvm:/dev/kvm
    privileged: true
    restart: unless-stopped

volumes:
  arangodb-data:
