services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=rootpassword
    ports:
      - "8529:8529"
    volumes:
      - arangodb-data:/var/lib/arangodb3
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-arango-backend
    environment:
      - ARANGO_HOST=http://arangodb:8529
      - ARANGO_USER=root
      - ARANGO_PASSWORD=rootpassword
      - ARANGO_DB=fastapi_arango_db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - arangodb
    command: ./wait-for-arangodb.sh http://arangodb:8529 poetry run python -m backend.main

volumes:
  arangodb-data:
      dockerfile: Dockerfile.android
    container_name: android-emulator
    network_mode: "host"
    environment:
      - ANDROID_HOME=/opt/android-sdk
    devices:
      - /dev/kvm:/dev/kvm
    privileged: true
    restart: unless-stopped

volumes:
  arangodb-data:
